#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SeekArc.Droid.Resource", IsApplication=false)]

namespace SeekArc.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public static int arcColor = 2130771977;
			
			// aapt resource value: 0x7f010004
			public static int arcWidth = 2130771972;
			
			// aapt resource value: 0x7f01000d
			public static int clockwise = 2130771981;
			
			// aapt resource value: 0x7f010002
			public static int max = 2130771970;
			
			// aapt resource value: 0x7f010005
			public static int progress = 2130771973;
			
			// aapt resource value: 0x7f01000a
			public static int progressColor = 2130771978;
			
			// aapt resource value: 0x7f010003
			public static int progressWidth = 2130771971;
			
			// aapt resource value: 0x7f010006
			public static int rotation = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public static int roundEdges = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public static int seekArcStyle = 2130771982;
			
			// aapt resource value: 0x7f010007
			public static int startAngle = 2130771975;
			
			// aapt resource value: 0x7f010008
			public static int sweepAngle = 2130771976;
			
			// aapt resource value: 0x7f010000
			public static int thumb = 2130771968;
			
			// aapt resource value: 0x7f010001
			public static int thumbOffset = 2130771969;
			
			// aapt resource value: 0x7f01000c
			public static int touchInside = 2130771980;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f030000
			public static int progress_gray = 2130903040;
			
			// aapt resource value: 0x7f030001
			public static int progress_gray_dark = 2130903041;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public static int scrubber_control_disabled_holo = 2130837504;
			
			// aapt resource value: 0x7f020001
			public static int scrubber_control_focused_holo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public static int scrubber_control_normal_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public static int scrubber_control_pressed_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public static int seek_arc_control_selector = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public static int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public static int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public static int SeekArc = 2131034112;
			
			// aapt resource value: 0x7f050001
			public static int SeekArcLight = 2131034113;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SeekArc = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 9
			public static int SeekArc_arcColor = 9;
			
			// aapt resource value: 4
			public static int SeekArc_arcWidth = 4;
			
			// aapt resource value: 13
			public static int SeekArc_clockwise = 13;
			
			// aapt resource value: 2
			public static int SeekArc_max = 2;
			
			// aapt resource value: 5
			public static int SeekArc_progress = 5;
			
			// aapt resource value: 10
			public static int SeekArc_progressColor = 10;
			
			// aapt resource value: 3
			public static int SeekArc_progressWidth = 3;
			
			// aapt resource value: 6
			public static int SeekArc_rotation = 6;
			
			// aapt resource value: 11
			public static int SeekArc_roundEdges = 11;
			
			// aapt resource value: 7
			public static int SeekArc_startAngle = 7;
			
			// aapt resource value: 8
			public static int SeekArc_sweepAngle = 8;
			
			// aapt resource value: 0
			public static int SeekArc_thumb = 0;
			
			// aapt resource value: 1
			public static int SeekArc_thumbOffset = 1;
			
			// aapt resource value: 12
			public static int SeekArc_touchInside = 12;
			
			public static int[] SeekArcTheme = new int[] {
					2130771982};
			
			// aapt resource value: 0
			public static int SeekArcTheme_seekArcStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
