#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DroidSeekArc.Demo.Resource", IsApplication=true)]

namespace DroidSeekArc.Demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::DroidSeekArc.Resource.Attribute.arcColor = global::DroidSeekArc.Demo.Resource.Attribute.arcColor;
			global::DroidSeekArc.Resource.Attribute.arcWidth = global::DroidSeekArc.Demo.Resource.Attribute.arcWidth;
			global::DroidSeekArc.Resource.Attribute.clockwise = global::DroidSeekArc.Demo.Resource.Attribute.clockwise;
			global::DroidSeekArc.Resource.Attribute.max = global::DroidSeekArc.Demo.Resource.Attribute.max;
			global::DroidSeekArc.Resource.Attribute.progress = global::DroidSeekArc.Demo.Resource.Attribute.progress;
			global::DroidSeekArc.Resource.Attribute.progressColor = global::DroidSeekArc.Demo.Resource.Attribute.progressColor;
			global::DroidSeekArc.Resource.Attribute.progressWidth = global::DroidSeekArc.Demo.Resource.Attribute.progressWidth;
			global::DroidSeekArc.Resource.Attribute.rotation = global::DroidSeekArc.Demo.Resource.Attribute.rotation;
			global::DroidSeekArc.Resource.Attribute.roundEdges = global::DroidSeekArc.Demo.Resource.Attribute.roundEdges;
			global::DroidSeekArc.Resource.Attribute.seekArcStyle = global::DroidSeekArc.Demo.Resource.Attribute.seekArcStyle;
			global::DroidSeekArc.Resource.Attribute.startAngle = global::DroidSeekArc.Demo.Resource.Attribute.startAngle;
			global::DroidSeekArc.Resource.Attribute.sweepAngle = global::DroidSeekArc.Demo.Resource.Attribute.sweepAngle;
			global::DroidSeekArc.Resource.Attribute.thumb = global::DroidSeekArc.Demo.Resource.Attribute.thumb;
			global::DroidSeekArc.Resource.Attribute.thumbOffset = global::DroidSeekArc.Demo.Resource.Attribute.thumbOffset;
			global::DroidSeekArc.Resource.Attribute.touchInside = global::DroidSeekArc.Demo.Resource.Attribute.touchInside;
			global::DroidSeekArc.Resource.Color.progress_gray = global::DroidSeekArc.Demo.Resource.Color.progress_gray;
			global::DroidSeekArc.Resource.Color.progress_gray_dark = global::DroidSeekArc.Demo.Resource.Color.progress_gray_dark;
			global::DroidSeekArc.Resource.Drawable.scrubber_control_disabled_holo = global::DroidSeekArc.Demo.Resource.Drawable.scrubber_control_disabled_holo;
			global::DroidSeekArc.Resource.Drawable.scrubber_control_focused_holo = global::DroidSeekArc.Demo.Resource.Drawable.scrubber_control_focused_holo;
			global::DroidSeekArc.Resource.Drawable.scrubber_control_normal_holo = global::DroidSeekArc.Demo.Resource.Drawable.scrubber_control_normal_holo;
			global::DroidSeekArc.Resource.Drawable.scrubber_control_pressed_holo = global::DroidSeekArc.Demo.Resource.Drawable.scrubber_control_pressed_holo;
			global::DroidSeekArc.Resource.Drawable.seek_arc_control_selector = global::DroidSeekArc.Demo.Resource.Drawable.seek_arc_control_selector;
			global::DroidSeekArc.Resource.String.ApplicationName = global::DroidSeekArc.Demo.Resource.String.ApplicationName;
			global::DroidSeekArc.Resource.String.Hello = global::DroidSeekArc.Demo.Resource.String.Hello;
			global::DroidSeekArc.Resource.Style.SeekArc = global::DroidSeekArc.Demo.Resource.Style.SeekArc;
			global::DroidSeekArc.Resource.Style.SeekArcLight = global::DroidSeekArc.Demo.Resource.Style.SeekArcLight;
			global::DroidSeekArc.Resource.Styleable.SeekArc = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc;
			global::DroidSeekArc.Resource.Styleable.SeekArc_arcColor = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_arcColor;
			global::DroidSeekArc.Resource.Styleable.SeekArc_arcWidth = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_arcWidth;
			global::DroidSeekArc.Resource.Styleable.SeekArc_clockwise = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_clockwise;
			global::DroidSeekArc.Resource.Styleable.SeekArc_max = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_max;
			global::DroidSeekArc.Resource.Styleable.SeekArc_progress = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_progress;
			global::DroidSeekArc.Resource.Styleable.SeekArc_progressColor = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_progressColor;
			global::DroidSeekArc.Resource.Styleable.SeekArc_progressWidth = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_progressWidth;
			global::DroidSeekArc.Resource.Styleable.SeekArc_rotation = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_rotation;
			global::DroidSeekArc.Resource.Styleable.SeekArc_roundEdges = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_roundEdges;
			global::DroidSeekArc.Resource.Styleable.SeekArc_startAngle = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_startAngle;
			global::DroidSeekArc.Resource.Styleable.SeekArc_sweepAngle = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_sweepAngle;
			global::DroidSeekArc.Resource.Styleable.SeekArc_thumb = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_thumb;
			global::DroidSeekArc.Resource.Styleable.SeekArc_thumbOffset = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_thumbOffset;
			global::DroidSeekArc.Resource.Styleable.SeekArc_touchInside = global::DroidSeekArc.Demo.Resource.Styleable.SeekArc_touchInside;
			global::DroidSeekArc.Resource.Styleable.SeekArcTheme = global::DroidSeekArc.Demo.Resource.Styleable.SeekArcTheme;
			global::DroidSeekArc.Resource.Styleable.SeekArcTheme_seekArcStyle = global::DroidSeekArc.Demo.Resource.Styleable.SeekArcTheme_seekArcStyle;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010009
			public const int arcColor = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int arcWidth = 2130771972;
			
			// aapt resource value: 0x7f01000d
			public const int clockwise = 2130771981;
			
			// aapt resource value: 0x7f010002
			public const int max = 2130771970;
			
			// aapt resource value: 0x7f010005
			public const int progress = 2130771973;
			
			// aapt resource value: 0x7f01000a
			public const int progressColor = 2130771978;
			
			// aapt resource value: 0x7f010003
			public const int progressWidth = 2130771971;
			
			// aapt resource value: 0x7f010006
			public const int rotation = 2130771974;
			
			// aapt resource value: 0x7f01000b
			public const int roundEdges = 2130771979;
			
			// aapt resource value: 0x7f01000e
			public const int seekArcStyle = 2130771982;
			
			// aapt resource value: 0x7f010007
			public const int startAngle = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int sweepAngle = 2130771976;
			
			// aapt resource value: 0x7f010000
			public const int thumb = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int thumbOffset = 2130771969;
			
			// aapt resource value: 0x7f01000c
			public const int touchInside = 2130771980;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int progress_gray = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int progress_gray_dark = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int scrubber_control_disabled_holo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int scrubber_control_focused_holo = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int scrubber_control_normal_holo = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int scrubber_control_pressed_holo = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int seek_arc_control_selector = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070000
			public const int seekArc = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int SeekArc = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int SeekArcLight = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SeekArc = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 9
			public const int SeekArc_arcColor = 9;
			
			// aapt resource value: 4
			public const int SeekArc_arcWidth = 4;
			
			// aapt resource value: 13
			public const int SeekArc_clockwise = 13;
			
			// aapt resource value: 2
			public const int SeekArc_max = 2;
			
			// aapt resource value: 5
			public const int SeekArc_progress = 5;
			
			// aapt resource value: 10
			public const int SeekArc_progressColor = 10;
			
			// aapt resource value: 3
			public const int SeekArc_progressWidth = 3;
			
			// aapt resource value: 6
			public const int SeekArc_rotation = 6;
			
			// aapt resource value: 11
			public const int SeekArc_roundEdges = 11;
			
			// aapt resource value: 7
			public const int SeekArc_startAngle = 7;
			
			// aapt resource value: 8
			public const int SeekArc_sweepAngle = 8;
			
			// aapt resource value: 0
			public const int SeekArc_thumb = 0;
			
			// aapt resource value: 1
			public const int SeekArc_thumbOffset = 1;
			
			// aapt resource value: 12
			public const int SeekArc_touchInside = 12;
			
			public static int[] SeekArcTheme = new int[] {
					2130771982};
			
			// aapt resource value: 0
			public const int SeekArcTheme_seekArcStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
